# Generated by Django 3.1.1 on 2020-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(default='0000000', help_text='Write here'),
        ),
    ]
